def generate_iges_wireframe_cube():
    start_section = "IGES wireframe cube generated by ChatGPT                                      S      1\n"
    global_section = (
        "1H,,1H;,,,,,15HChatGPT Cube IGES,,32,38,6,308,15H20251001.120000,1.0,1.0,1.0,1.0,1.0;   G      1\n"
    )
    
    de_lines = ""
    for i in range(1, 13):
        line1 = f"     110{i:7d}       0       0       0       0       0       0       {i:7d}       0D      1\n"
        line2 = f"     110{i:7d}       0       0       0       0       0       0       {i:7d}       0D      2\n"
        de_lines += line1 + line2
    
    vertices = [
        (-0.5, -0.5, -0.5),
        ( 0.5, -0.5, -0.5),
        ( 0.5,  0.5, -0.5),
        (-0.5,  0.5, -0.5),
        (-0.5, -0.5,  0.5),
        ( 0.5, -0.5,  0.5),
        ( 0.5,  0.5,  0.5),
        (-0.5,  0.5,  0.5),
    ]
    
    edges = [
        (0, 1), (1, 2), (2, 3), (3, 0),
        (4, 5), (5, 6), (6, 7), (7, 4),
        (0, 4), (1, 5), (2, 6), (3, 7),
    ]
    
    pd_lines = ""
    for i, (start, end) in enumerate(edges, start=1):
        x1, y1, z1 = vertices[start]
        x2, y2, z2 = vertices[end]
        pd_lines += f"110,{x1},{y1},{z1},{x2},{y2},{z2};{' '*(70)}P{str(i).rjust(6)}\n"
    
    terminate_section = f"S      1G      1D     24P     12                                                     T      1\n"
    
    iges_content = start_section + global_section + de_lines + pd_lines + terminate_section
    
    with open("cube_wireframe.igs", "w") as f:
        f.write(iges_content)
    print("IGES wireframe cube saved as cube_wireframe.igs")

# Uncomment and run if you want to create the file via Python:
generate_iges_wireframe_cube()